`timescale 1ns/1ps
// ============================================================================
//  sine_lut.v  -  Tabela de seno / Sine look-up table
// ----------------------------------------------------------------------------
//  256 amostras de uma senoide completa, amplitude +/-120, formato Q0.7 com
//  sinal (complemento de dois, 8 bits). Endereco = fase (0..255 = 0..360deg).
//
//  256 samples of one full sine period, amplitude +/-120, signed 8-bit
//  (two's complement). Address = phase (0..255 maps to 0..360 degrees).
//
//  O arquivo "sine_lut.hex" e gerado por model/gen_sine.py (e tambem pelo
//  modelo de referencia em Python), garantindo que hardware e simulacao usem
//  EXATAMENTE a mesma tabela. / The hex file is generated by Python so that
//  hardware and the reference model share the EXACT same table.
// ============================================================================
`default_nettype none

module sine_lut (
    input  wire        clk,
    input  wire [7:0]  phase,   // 0..255  -> 0..2*pi
    output reg  signed [7:0] value
);
    reg signed [7:0] rom [0:255];
    initial $readmemh("sine_lut.hex", rom);

    always @(posedge clk)
        value <= rom[phase];
endmodule
`default_nettype wire
